name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
      with:
        lfs: true

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GHP_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: .
        CLEAN: true

